$(document).ready(function(){
  $(".owl-carousel").owlCarousel({
  	autoplay:true,
  	autoplayTimeout:5000,
  	autoplayHoverPause:false,
  	margin:15,
  	responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
  });
});